name: Email Notifications
on:
  push:
    branches:
      - master
jobs:
  redo:
    runs-on: ubuntu-latest
    steps:
        - name: redo
          run: echo "Redoing the noftification"
        - name: checks out the repository
          uses: actions/checkout@v4     
      
        - name: Post to a Slack channel
          id: slack
          uses: slackapi/slack-github-action@v1.24.0
          with:
             # Slack channel id, channel name, or user id to post message.
             # See also: https://api.slack.com/methods/chat.postMessage#channels
             # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
             channel-id: 'C067S5EPGQ2'
             # For posting a simple plain text message
             slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
             env:
             SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        - name: Send mail
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: Github Actions job result
            to: yemilabodey@yahoo.com
            from: yemi olabodey # yemilabodey@gmail.com
            body: Build job of ${{github.repository}} completed successfully!

        - name: "Logs into docker"
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: "Build our code"
          env:
             IMAGE_NAME: simplepersonal1m
             VERSION: latest
             USERNAME: blaqgoldmine
          run: |
            docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
            docker push $USERNAME/$IMAGE_NAME:$VERSION